name: Build Test
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up cache
              uses: actions/cache@v2
              with:
                  path: ~/.bun
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/lockfiles') }}

            - name: Install dependencies
              run: npm i -g bun; bun i

            - name: Build
              run: bun run build

            - name: Test
              if: ${{ success() }}
              run: bun run test
